"""Tornado handlers for serving FreeBrowse static files."""

import os
from tornado.web import StaticFileHandler

HERE = os.path.dirname(__file__)
STATIC_DIR = os.path.join(HERE, "static", "freebrowse")


def setup_handlers(web_app, log=None):
    """Register the /freebrowse/ static file handler.

    The bundle under ``static/freebrowse`` is generated by ``npm run build:jupyter``
    in ``../frontend`` and is not committed, so a fresh checkout has nothing to
    serve until that build has run. Say so at startup instead of answering 404s.
    """
    if not os.path.isfile(os.path.join(STATIC_DIR, "index.html")):
        msg = (
            f"jupyterlab_freebrowse: no FreeBrowse bundle at {STATIC_DIR}; "
            "run `npm run build:jupyter` in the frontend/ directory, then "
            "reinstall (pip install -e .) or restart the server."
        )
        if log is not None:
            log.warning(msg)
        else:
            print(msg)
    base_url = web_app.settings.get("base_url", "/")
    route_pattern = rf"{base_url}freebrowse/(.*)"

    web_app.add_handlers(
        r".*",
        [
            (
                route_pattern,
                StaticFileHandler,
                {"path": STATIC_DIR, "default_filename": "index.html"},
            )
        ],
    )
